# Generated by Django 4.2.11 on 2026-01-26 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_text', models.TextField(verbose_name='Recommendation text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='authentication.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.IntegerField(help_text='Calculated risk tolerance score from questionnaire', verbose_name='Risk score (0-100)')),
                ('risk_category', models.CharField(choices=[('Conservative', 'Conservative (0-30%)'), ('Moderate', 'Moderate (31-60%)'), ('Growth', 'Growth (61-80%)'), ('Aggressive', 'Aggressive (81-100%)')], max_length=20, verbose_name='Risk category')),
                ('asset_allocation', models.JSONField(help_text='JSON object with allocation percentages: {"stocks": 60, "bonds": 25, "cash": 10, "alternatives": 5}', verbose_name='Asset allocation')),
                ('recommendations', models.JSONField(help_text='JSON array of recommendation strings', verbose_name='Investment recommendations')),
                ('key_traits', models.JSONField(help_text='JSON array of trait strings', verbose_name='Key personality traits')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_profile', to='authentication.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Investment Profile',
                'verbose_name_plural': 'Investment Profiles',
                'ordering': ['-updated_at'],
            },
        ),
    ]
